[project]
name = "data-studies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groq>=1.0.0",
    "ipykernel>=7.2.0",
    "streamlit>=1.54.0",
    "watermark>=2.6.0",
]
